package flysong.rgb.init;

import flysong.rgb.rgb;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@Mod.EventBusSubscriber(modid = rgb.MODID)
public class BlockLoader {
    public static Block a0 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_000_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a1 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_000_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a2 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_000_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a3 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_000_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a4 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_000_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a5 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_064_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a6 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_064_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a7 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_064_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a8 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_064_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a9 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_064_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a10 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_128_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a11 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_128_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a12 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_128_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a13 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_128_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a14 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_128_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a15 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_192_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a16 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_192_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a17 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_192_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a18 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_192_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a19 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_192_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a20 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_255_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a21 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_255_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a22 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_255_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a23 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_255_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a24 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("000_255_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a25 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_000_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a26 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_000_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a27 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_000_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a28 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_000_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a29 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_000_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a30 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_064_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a31 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_064_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a32 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_064_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a33 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_064_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a34 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_064_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a35 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_128_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a36 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_128_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a37 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_128_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a38 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_128_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a39 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_128_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a40 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_192_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a41 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_192_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a42 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_192_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a43 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_192_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a44 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_192_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a45 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_255_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a46 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_255_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a47 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_255_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a48 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_255_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a49 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("064_255_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a50 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_000_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a51 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_000_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a52 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_000_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a53 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_000_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a54 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_000_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a55 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_064_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a56 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_064_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a57 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_064_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a58 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_064_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a59 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_064_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a60 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_128_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a61 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_128_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a62 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_128_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a63 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_128_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a64 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_128_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a65 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_192_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a66 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_192_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a67 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_192_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a68 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_192_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a69 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_192_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a70 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_255_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a71 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_255_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a72 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_255_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a73 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_255_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a74 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("128_255_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a75 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_000_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a76 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_000_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a77 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_000_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a78 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_000_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a79 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_000_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a80 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_064_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a81 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_064_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a82 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_064_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a83 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_064_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a84 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_064_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a85 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_128_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a86 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_128_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a87 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_128_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a88 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_128_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a89 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_128_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a90 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_192_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a91 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_192_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a92 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_192_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a93 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_192_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a94 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_192_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a95 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_255_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a96 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_255_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a97 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_255_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a98 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_255_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a99 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("192_255_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a100 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_000_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a101 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_000_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a102 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_000_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a103 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_000_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a104 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_000_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a105 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_064_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a106 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_064_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a107 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_064_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a108 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_064_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a109 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_064_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a110 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_128_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a111 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_128_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a112 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_128_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a113 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_128_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a114 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_128_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a115 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_192_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a116 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_192_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a117 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_192_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a118 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_192_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a119 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_192_255").setCreativeTab(CTLoader.ColorBlock);
    public static Block a120 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_255_000").setCreativeTab(CTLoader.ColorBlock);
    public static Block a121 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_255_064").setCreativeTab(CTLoader.ColorBlock);
    public static Block a122 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_255_128").setCreativeTab(CTLoader.ColorBlock);
    public static Block a123 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_255_192").setCreativeTab(CTLoader.ColorBlock);
    public static Block a124 = new Block(Material.ROCK).setUnlocalizedName("rgbColorBlock").setRegistryName("255_255_255").setCreativeTab(CTLoader.ColorBlock);

    public BlockLoader()
    {
        MinecraftForge.EVENT_BUS.register(this);
    }

    @SubscribeEvent
    public static void Loader(RegistryEvent.Register<Block> event) {
        event.getRegistry().registerAll(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32,a33,a34,a35,a36,a37,a38,a39,a40,a41,a42,a43,a44,a45,a46,a47,a48,a49,a50,a51,a52,a53,a54,a55,a56,a57,a58,a59,a60,a61,a62,a63,a64,a65,a66,a67,a68,a69,a70,a71,a72,a73,a74,a75,a76,a77,a78,a79,a80,a81,a82,a83,a84,a85,a86,a87,a88,a89,a90,a91,a92,a93,a94,a95,a96,a97,a98,a99,a100,a101,a102,a103,a104,a105,a106,a107,a108,a109,a110,a111,a112,a113,a114,a115,a116,a117,a118,a119,a120,a121,a122,a123,a124);
    }
}
