package flysong.rgb.init;

import flysong.rgb.rgb;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

import static flysong.rgb.init.BlockLoader.*;

@Mod.EventBusSubscriber(modid = rgb.MODID)
public class ItemLoader {
    public static final Item Ia0 = new ItemBlock(a0).setRegistryName(a0.getRegistryName());
    public static final Item Ia1 = new ItemBlock(a1).setRegistryName(a1.getRegistryName());
    public static final Item Ia2 = new ItemBlock(a2).setRegistryName(a2.getRegistryName());
    public static final Item Ia3 = new ItemBlock(a3).setRegistryName(a3.getRegistryName());
    public static final Item Ia4 = new ItemBlock(a4).setRegistryName(a4.getRegistryName());
    public static final Item Ia5 = new ItemBlock(a5).setRegistryName(a5.getRegistryName());
    public static final Item Ia6 = new ItemBlock(a6).setRegistryName(a6.getRegistryName());
    public static final Item Ia7 = new ItemBlock(a7).setRegistryName(a7.getRegistryName());
    public static final Item Ia8 = new ItemBlock(a8).setRegistryName(a8.getRegistryName());
    public static final Item Ia9 = new ItemBlock(a9).setRegistryName(a9.getRegistryName());
    public static final Item Ia10 = new ItemBlock(a10).setRegistryName(a10.getRegistryName());
    public static final Item Ia11 = new ItemBlock(a11).setRegistryName(a11.getRegistryName());
    public static final Item Ia12 = new ItemBlock(a12).setRegistryName(a12.getRegistryName());
    public static final Item Ia13 = new ItemBlock(a13).setRegistryName(a13.getRegistryName());
    public static final Item Ia14 = new ItemBlock(a14).setRegistryName(a14.getRegistryName());
    public static final Item Ia15 = new ItemBlock(a15).setRegistryName(a15.getRegistryName());
    public static final Item Ia16 = new ItemBlock(a16).setRegistryName(a16.getRegistryName());
    public static final Item Ia17 = new ItemBlock(a17).setRegistryName(a17.getRegistryName());
    public static final Item Ia18 = new ItemBlock(a18).setRegistryName(a18.getRegistryName());
    public static final Item Ia19 = new ItemBlock(a19).setRegistryName(a19.getRegistryName());
    public static final Item Ia20 = new ItemBlock(a20).setRegistryName(a20.getRegistryName());
    public static final Item Ia21 = new ItemBlock(a21).setRegistryName(a21.getRegistryName());
    public static final Item Ia22 = new ItemBlock(a22).setRegistryName(a22.getRegistryName());
    public static final Item Ia23 = new ItemBlock(a23).setRegistryName(a23.getRegistryName());
    public static final Item Ia24 = new ItemBlock(a24).setRegistryName(a24.getRegistryName());
    public static final Item Ia25 = new ItemBlock(a25).setRegistryName(a25.getRegistryName());
    public static final Item Ia26 = new ItemBlock(a26).setRegistryName(a26.getRegistryName());
    public static final Item Ia27 = new ItemBlock(a27).setRegistryName(a27.getRegistryName());
    public static final Item Ia28 = new ItemBlock(a28).setRegistryName(a28.getRegistryName());
    public static final Item Ia29 = new ItemBlock(a29).setRegistryName(a29.getRegistryName());
    public static final Item Ia30 = new ItemBlock(a30).setRegistryName(a30.getRegistryName());
    public static final Item Ia31 = new ItemBlock(a31).setRegistryName(a31.getRegistryName());
    public static final Item Ia32 = new ItemBlock(a32).setRegistryName(a32.getRegistryName());
    public static final Item Ia33 = new ItemBlock(a33).setRegistryName(a33.getRegistryName());
    public static final Item Ia34 = new ItemBlock(a34).setRegistryName(a34.getRegistryName());
    public static final Item Ia35 = new ItemBlock(a35).setRegistryName(a35.getRegistryName());
    public static final Item Ia36 = new ItemBlock(a36).setRegistryName(a36.getRegistryName());
    public static final Item Ia37 = new ItemBlock(a37).setRegistryName(a37.getRegistryName());
    public static final Item Ia38 = new ItemBlock(a38).setRegistryName(a38.getRegistryName());
    public static final Item Ia39 = new ItemBlock(a39).setRegistryName(a39.getRegistryName());
    public static final Item Ia40 = new ItemBlock(a40).setRegistryName(a40.getRegistryName());
    public static final Item Ia41 = new ItemBlock(a41).setRegistryName(a41.getRegistryName());
    public static final Item Ia42 = new ItemBlock(a42).setRegistryName(a42.getRegistryName());
    public static final Item Ia43 = new ItemBlock(a43).setRegistryName(a43.getRegistryName());
    public static final Item Ia44 = new ItemBlock(a44).setRegistryName(a44.getRegistryName());
    public static final Item Ia45 = new ItemBlock(a45).setRegistryName(a45.getRegistryName());
    public static final Item Ia46 = new ItemBlock(a46).setRegistryName(a46.getRegistryName());
    public static final Item Ia47 = new ItemBlock(a47).setRegistryName(a47.getRegistryName());
    public static final Item Ia48 = new ItemBlock(a48).setRegistryName(a48.getRegistryName());
    public static final Item Ia49 = new ItemBlock(a49).setRegistryName(a49.getRegistryName());
    public static final Item Ia50 = new ItemBlock(a50).setRegistryName(a50.getRegistryName());
    public static final Item Ia51 = new ItemBlock(a51).setRegistryName(a51.getRegistryName());
    public static final Item Ia52 = new ItemBlock(a52).setRegistryName(a52.getRegistryName());
    public static final Item Ia53 = new ItemBlock(a53).setRegistryName(a53.getRegistryName());
    public static final Item Ia54 = new ItemBlock(a54).setRegistryName(a54.getRegistryName());
    public static final Item Ia55 = new ItemBlock(a55).setRegistryName(a55.getRegistryName());
    public static final Item Ia56 = new ItemBlock(a56).setRegistryName(a56.getRegistryName());
    public static final Item Ia57 = new ItemBlock(a57).setRegistryName(a57.getRegistryName());
    public static final Item Ia58 = new ItemBlock(a58).setRegistryName(a58.getRegistryName());
    public static final Item Ia59 = new ItemBlock(a59).setRegistryName(a59.getRegistryName());
    public static final Item Ia60 = new ItemBlock(a60).setRegistryName(a60.getRegistryName());
    public static final Item Ia61 = new ItemBlock(a61).setRegistryName(a61.getRegistryName());
    public static final Item Ia62 = new ItemBlock(a62).setRegistryName(a62.getRegistryName());
    public static final Item Ia63 = new ItemBlock(a63).setRegistryName(a63.getRegistryName());
    public static final Item Ia64 = new ItemBlock(a64).setRegistryName(a64.getRegistryName());
    public static final Item Ia65 = new ItemBlock(a65).setRegistryName(a65.getRegistryName());
    public static final Item Ia66 = new ItemBlock(a66).setRegistryName(a66.getRegistryName());
    public static final Item Ia67 = new ItemBlock(a67).setRegistryName(a67.getRegistryName());
    public static final Item Ia68 = new ItemBlock(a68).setRegistryName(a68.getRegistryName());
    public static final Item Ia69 = new ItemBlock(a69).setRegistryName(a69.getRegistryName());
    public static final Item Ia70 = new ItemBlock(a70).setRegistryName(a70.getRegistryName());
    public static final Item Ia71 = new ItemBlock(a71).setRegistryName(a71.getRegistryName());
    public static final Item Ia72 = new ItemBlock(a72).setRegistryName(a72.getRegistryName());
    public static final Item Ia73 = new ItemBlock(a73).setRegistryName(a73.getRegistryName());
    public static final Item Ia74 = new ItemBlock(a74).setRegistryName(a74.getRegistryName());
    public static final Item Ia75 = new ItemBlock(a75).setRegistryName(a75.getRegistryName());
    public static final Item Ia76 = new ItemBlock(a76).setRegistryName(a76.getRegistryName());
    public static final Item Ia77 = new ItemBlock(a77).setRegistryName(a77.getRegistryName());
    public static final Item Ia78 = new ItemBlock(a78).setRegistryName(a78.getRegistryName());
    public static final Item Ia79 = new ItemBlock(a79).setRegistryName(a79.getRegistryName());
    public static final Item Ia80 = new ItemBlock(a80).setRegistryName(a80.getRegistryName());
    public static final Item Ia81 = new ItemBlock(a81).setRegistryName(a81.getRegistryName());
    public static final Item Ia82 = new ItemBlock(a82).setRegistryName(a82.getRegistryName());
    public static final Item Ia83 = new ItemBlock(a83).setRegistryName(a83.getRegistryName());
    public static final Item Ia84 = new ItemBlock(a84).setRegistryName(a84.getRegistryName());
    public static final Item Ia85 = new ItemBlock(a85).setRegistryName(a85.getRegistryName());
    public static final Item Ia86 = new ItemBlock(a86).setRegistryName(a86.getRegistryName());
    public static final Item Ia87 = new ItemBlock(a87).setRegistryName(a87.getRegistryName());
    public static final Item Ia88 = new ItemBlock(a88).setRegistryName(a88.getRegistryName());
    public static final Item Ia89 = new ItemBlock(a89).setRegistryName(a89.getRegistryName());
    public static final Item Ia90 = new ItemBlock(a90).setRegistryName(a90.getRegistryName());
    public static final Item Ia91 = new ItemBlock(a91).setRegistryName(a91.getRegistryName());
    public static final Item Ia92 = new ItemBlock(a92).setRegistryName(a92.getRegistryName());
    public static final Item Ia93 = new ItemBlock(a93).setRegistryName(a93.getRegistryName());
    public static final Item Ia94 = new ItemBlock(a94).setRegistryName(a94.getRegistryName());
    public static final Item Ia95 = new ItemBlock(a95).setRegistryName(a95.getRegistryName());
    public static final Item Ia96 = new ItemBlock(a96).setRegistryName(a96.getRegistryName());
    public static final Item Ia97 = new ItemBlock(a97).setRegistryName(a97.getRegistryName());
    public static final Item Ia98 = new ItemBlock(a98).setRegistryName(a98.getRegistryName());
    public static final Item Ia99 = new ItemBlock(a99).setRegistryName(a99.getRegistryName());
    public static final Item Ia100 = new ItemBlock(a100).setRegistryName(a100.getRegistryName());
    public static final Item Ia101 = new ItemBlock(a101).setRegistryName(a101.getRegistryName());
    public static final Item Ia102 = new ItemBlock(a102).setRegistryName(a102.getRegistryName());
    public static final Item Ia103 = new ItemBlock(a103).setRegistryName(a103.getRegistryName());
    public static final Item Ia104 = new ItemBlock(a104).setRegistryName(a104.getRegistryName());
    public static final Item Ia105 = new ItemBlock(a105).setRegistryName(a105.getRegistryName());
    public static final Item Ia106 = new ItemBlock(a106).setRegistryName(a106.getRegistryName());
    public static final Item Ia107 = new ItemBlock(a107).setRegistryName(a107.getRegistryName());
    public static final Item Ia108 = new ItemBlock(a108).setRegistryName(a108.getRegistryName());
    public static final Item Ia109 = new ItemBlock(a109).setRegistryName(a109.getRegistryName());
    public static final Item Ia110 = new ItemBlock(a110).setRegistryName(a110.getRegistryName());
    public static final Item Ia111 = new ItemBlock(a111).setRegistryName(a111.getRegistryName());
    public static final Item Ia112 = new ItemBlock(a112).setRegistryName(a112.getRegistryName());
    public static final Item Ia113 = new ItemBlock(a113).setRegistryName(a113.getRegistryName());
    public static final Item Ia114 = new ItemBlock(a114).setRegistryName(a114.getRegistryName());
    public static final Item Ia115 = new ItemBlock(a115).setRegistryName(a115.getRegistryName());
    public static final Item Ia116 = new ItemBlock(a116).setRegistryName(a116.getRegistryName());
    public static final Item Ia117 = new ItemBlock(a117).setRegistryName(a117.getRegistryName());
    public static final Item Ia118 = new ItemBlock(a118).setRegistryName(a118.getRegistryName());
    public static final Item Ia119 = new ItemBlock(a119).setRegistryName(a119.getRegistryName());
    public static final Item Ia120 = new ItemBlock(a120).setRegistryName(a120.getRegistryName());
    public static final Item Ia121 = new ItemBlock(a121).setRegistryName(a121.getRegistryName());
    public static final Item Ia122 = new ItemBlock(a122).setRegistryName(a122.getRegistryName());
    public static final Item Ia123 = new ItemBlock(a123).setRegistryName(a123.getRegistryName());
    public static final Item Ia124 = new ItemBlock(a124).setRegistryName(a124.getRegistryName());

    public ItemLoader()
    {
        MinecraftForge.EVENT_BUS.register(this);
    }

    @SubscribeEvent
    public static void Loader(RegistryEvent.Register<Item> event) {
        event.getRegistry().registerAll(Ia0,Ia1,Ia2,Ia3,Ia4,Ia5,Ia6,Ia7,Ia8,Ia9,Ia10,Ia11,Ia12,Ia13,Ia14,Ia15,Ia16,Ia17,Ia18,Ia19,Ia20,Ia21,Ia22,Ia23,Ia24,Ia25,Ia26,Ia27,Ia28,Ia29,Ia30,Ia31,Ia32,Ia33,Ia34,Ia35,Ia36,Ia37,Ia38,Ia39,Ia40,Ia41,Ia42,Ia43,Ia44,Ia45,Ia46,Ia47,Ia48,Ia49,Ia50,Ia51,Ia52,Ia53,Ia54,Ia55,Ia56,Ia57,Ia58,Ia59,Ia60,Ia61,Ia62,Ia63,Ia64,Ia65,Ia66,Ia67,Ia68,Ia69,Ia70,Ia71,Ia72,Ia73,Ia74,Ia75,Ia76,Ia77,Ia78,Ia79,Ia80,Ia81,Ia82,Ia83,Ia84,Ia85,Ia86,Ia87,Ia88,Ia89,Ia90,Ia91,Ia92,Ia93,Ia94,Ia95,Ia96,Ia97,Ia98,Ia99,Ia100,Ia101,Ia102,Ia103,Ia104,Ia105,Ia106,Ia107,Ia108,Ia109,Ia110,Ia111,Ia112,Ia113,Ia114,Ia115,Ia116,Ia117,Ia118,Ia119,Ia120,Ia121,Ia122,Ia123,Ia124);
    }
}
